version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - local_network

  redis:
    image: redis:7-alpine
    container_name: redis-db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - local_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      APP_PORT: 3000
      APP_ENV: production
      JWT_ACCESS_SECRET: super_secret_jwt_access_key
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET:super_secret_jwt_refresh_key
      JWT_REFRESH_EXPIRES_IN: 7d
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: personal_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3000:3000"
    networks:
      - local_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - local_network

volumes:
  mysql_data:
  redis_data:

networks:
  local_network:
    driver: bridge
